const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={backend:'',accounts:[],jobs:[],selected:new Set(),mode:'random',pickedFiles:[],uploading:false,lastUploadError:'',health:null,storage:null,drive:null};
const ACTIVE=new Set(['scheduled','processing','ready','publishing','retry_wait']);
// Keep the old DB name so pending uploads from v12 survive this upgrade.
const DB_NAME='iap_mobile_v12', STORE='uploadBatches';

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3000)}
function cleanUrl(v){return String(v||'').trim().replace(/\/+$/,'')}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(d){try{return new Date(d).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}catch{return d||''}}
function statusClass(s){return ['published','failed','retry_wait'].includes(s)?s:''}
async function api(path,opts={}){if(!state.backend)throw new Error('Backend URL save karo.');const r=await fetch(state.backend+path,opts);let j={};const txt=await r.text();try{j=txt?JSON.parse(txt):{}}catch{j={error:txt||`HTTP ${r.status}`}}if(!r.ok)throw new Error(j.error||j.message||`HTTP ${r.status}`);return j}

function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(['published','queue','accounts'].includes(name))refreshAll(false)}
$$('.navbtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function setServer(ok){const p=$('#serverPill');p.textContent=ok?'Server online':'Server offline';p.className='pill '+(ok?'online':'offline')}

function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE,{keyPath:'id'})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbPut(v){const db=await openDb();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(v);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function dbDelete(id){const db=await openDb();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).delete(id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function dbAll(){const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}

function backupKey(){return 'iap_recovery_'+btoa(state.backend).replace(/=/g,'')}
function selKey(){return 'iap_selected_'+btoa(state.backend).replace(/=/g,'')}
async function mirrorRecovery(){if(!state.backend)return;try{const pack=await api('/api/accounts/recovery-pack');if(pack.backups?.length)localStorage.setItem(backupKey(),JSON.stringify(pack.backups.map(x=>x.backupBlob)))}catch{}}
async function tryRestore(){if(!state.backend)return[];try{let accts=await api('/api/accounts');if(accts.length){await mirrorRecovery();return accts}const raw=localStorage.getItem(backupKey());const backups=raw?JSON.parse(raw):[];if(backups.length){await api('/api/accounts/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backups})});accts=await api('/api/accounts');if(accts.length)toast(`Recovered ${accts.length} account(s)`)}return accts}catch{return[]}}
function loadSelection(){try{state.selected=new Set(JSON.parse(localStorage.getItem(selKey())||'[]'))}catch{state.selected=new Set()}}
function saveSelection(){localStorage.setItem(selKey(),JSON.stringify([...state.selected]))}

async function refreshSystem(){if(!state.backend)return;try{state.health=await api('/api/health')}catch{state.health=null}try{state.storage=await api('/api/storage-status')}catch{state.storage=null}try{state.drive=await api('/api/google-drive/connect-info')}catch{state.drive=null}renderSystem()}
async function refreshAll(showErr=true){if(!state.backend){setServer(false);return}try{state.health=await api('/api/health');setServer(true);state.accounts=await tryRestore();loadSelection();state.selected=new Set([...state.selected].filter(id=>state.accounts.some(a=>a.id===id)));state.jobs=await api('/api/jobs');try{state.storage=await api('/api/storage-status')}catch{}try{state.drive=await api('/api/google-drive/connect-info')}catch{}render();await mirrorRecovery();resumeUploads()}catch(e){setServer(false);if(showErr)toast(e.message)}}
function render(){renderStats();renderAccounts();renderChips();renderQueue();renderPublished();renderNext();renderUploadMini();renderSystem()}

function renderStats(){const active=state.jobs.filter(j=>ACTIVE.has(j.status)).length;$('#statAccounts').textContent=state.accounts.length;$('#statScheduled').textContent=active;$('#statPublished').textContent=state.jobs.filter(j=>j.status==='published').length;$('#statFailed').textContent=state.jobs.filter(j=>j.status==='failed').length}
function renderSystem(){const st=state.storage, dr=state.drive, h=state.health;$('#backendVersion').textContent=h?`Backend v${h.version||'?'} · ${h.mediaStorage||st?.media||'?'}`:'Backend status unavailable';$('#stateStorage').textContent=st?.state||'—';$('#mediaStorage').textContent=st?.media||'—';$('#restartSafe').textContent=st?String(!!st.restartSafe):'—';$('#driveConnected').textContent=dr?String(!!dr.connected):'—';const p=$('#storagePill');const safe=!!st?.safeToSchedule;p.textContent=safe?'Storage safe':'Storage check';p.className='pill '+(safe?'online':'offline');let msg='';if(st?.exactTimingWarning)msg=st.exactTimingWarning;else if(st?.reasons?.length)msg=st.reasons.join(' ');else if(safe)msg='Postgres + durable media are ready for bulk scheduling.';$('#storageMessage').textContent=msg}
function renderChips(){const el=$('#accountChips');if(!state.accounts.length){el.innerHTML='<span class="sub">No connected accounts.</span>';return}el.innerHTML=state.accounts.map(a=>`<label class="chip"><input type="checkbox" data-acct="${a.id}" ${state.selected.has(a.id)?'checked':''}>@${esc(a.label)}</label>`).join('');el.querySelectorAll('input').forEach(i=>i.onchange=()=>{i.checked?state.selected.add(i.dataset.acct):state.selected.delete(i.dataset.acct);saveSelection()})}
function renderAccounts(){const el=$('#accountsList');if(!state.accounts.length){el.innerHTML='<div class="empty">No connected accounts.</div>';return}el.innerHTML=state.accounts.map(a=>`<div class="accountrow"><div class="grow"><strong>@${esc(a.label)}</strong><span>${esc(a.igUserId)}</span></div><button class="btn small red" data-removeacct="${a.id}">Remove</button></div>`).join('');el.querySelectorAll('[data-removeacct]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this account?'))return;try{await api('/api/accounts/'+b.dataset.removeacct,{method:'DELETE'});state.selected.delete(b.dataset.removeacct);saveSelection();await refreshAll()}catch(e){toast(e.message)}})}

function renderQueue(){const el=$('#queueList');if(!el)return;const q=$('#queueSearch').value.trim().toLowerCase(),f=$('#queueFilter').value;let jobs=state.jobs.filter(j=>j.status!=='published');if(f==='active')jobs=jobs.filter(j=>ACTIVE.has(j.status));else if(f!=='all')jobs=jobs.filter(j=>j.status===f);if(q)jobs=jobs.filter(j=>(String(j.fileName||'')+' '+String(j.accountLabel||'')).toLowerCase().includes(q));jobs.sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));if(!jobs.length){el.innerHTML='<div class="empty">No matching jobs.</div>';return}el.innerHTML=jobs.slice(0,500).map(j=>`<div class="job"><div class="jobtop"><div class="grow"><div class="jobname">${esc(j.fileName)}</div><div class="jobmeta">@${esc(j.accountLabel)} · ${fmt(j.scheduledAt)}</div>${j.error?`<div class="jobmeta errtxt">${esc(j.error)}</div>`:''}</div><span class="status ${statusClass(j.status)}">${esc(j.status)}</span></div><div class="jobactions">${!['processing','publishing','published'].includes(j.status)?`<button class="btn small purple" data-now="${j.id}">⚡ Post Now</button>`:''}${!['processing','publishing','published'].includes(j.status)?`<button class="btn small red" data-del="${j.id}">🗑 Delete</button>`:''}${j.status==='failed'?`<button class="btn small ghost" data-retry="${j.id}">↻ Retry</button>`:''}</div></div>`).join('');el.querySelectorAll('[data-now]').forEach(b=>b.onclick=()=>jobAction(b.dataset.now,'post-now'));el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteJob(b.dataset.del));el.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>jobAction(b.dataset.retry,'retry'))}
async function jobAction(id,act){try{await api(`/api/jobs/${id}/${act}`,{method:'POST'});toast(act==='post-now'?'Moved to Post Now queue':'Retry queued');await refreshAll(false)}catch(e){toast(e.message)}}
async function deleteJob(id){if(!confirm('Delete this scheduled job?'))return;try{await api('/api/jobs/'+id,{method:'DELETE'});toast('Deleted');await refreshAll(false)}catch(e){toast(e.message)}}
async function deleteAllFailed(){const failed=state.jobs.filter(j=>j.status==='failed');if(!failed.length){toast('No failed jobs.');return}if(!confirm(`Delete ${failed.length} failed jobs?`))return;let n=0;for(const j of failed){try{await api('/api/jobs/'+j.id,{method:'DELETE'});n++}catch{}}toast(`Deleted ${n} failed jobs`);await refreshAll(false)}
function renderPublished(){const el=$('#publishedList');if(!el)return;const jobs=state.jobs.filter(j=>j.status==='published').sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0));if(!jobs.length){el.innerHTML='<div class="empty">No published posts yet.</div>';return}el.innerHTML=jobs.slice(0,400).map(j=>`<div class="job pub"><div class="pubicon">🎬</div><div class="grow"><div class="jobname">${esc(j.fileName)}</div><div class="jobmeta">@${esc(j.accountLabel)} · ${fmt(j.publishedAt||j.scheduledAt)}</div><div class="jobactions">${j.permalink?`<a class="btn small green" target="_blank" rel="noopener" href="${esc(j.permalink)}">View on Instagram ↗</a>`:'<span class="tiny">Permalink pending…</span>'}</div></div></div>`).join('')}

let nextJob=null;
function renderNext(){const now=Date.now();const arr=state.jobs.filter(j=>ACTIVE.has(j.status)&&new Date(j.scheduledAt).getTime()>=now-60000).sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));nextJob=arr[0]||null;$('#nextPostMeta').textContent=nextJob?`@${nextJob.accountLabel} · ${nextJob.fileName}`:'No scheduled job';updateCountdown()}
function updateCountdown(){if(!nextJob){$('#countdown').textContent='--:--';return}let s=Math.max(0,Math.floor((new Date(nextJob.scheduledAt)-Date.now())/1000));const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),sec=s%60;$('#countdown').textContent=(h?`${h}h `:'')+`${String(m).padStart(2,'0')}m ${String(sec).padStart(2,'0')}s`}
setInterval(updateCountdown,1000);

function makeTimePicker(id,h=9,m=0,ap='AM'){const el=$('#'+id);const hs=Array.from({length:12},(_,i)=>i+1).map(v=>`<option ${v===h?'selected':''}>${v}</option>`).join('');const ms=Array.from({length:60},(_,i)=>i).map(v=>`<option value="${v}" ${v===m?'selected':''}>${String(v).padStart(2,'0')}</option>`).join('');el.innerHTML=`<select class="select h">${hs}</select><b>:</b><select class="select m">${ms}</select><select class="select ap"><option ${ap==='AM'?'selected':''}>AM</option><option ${ap==='PM'?'selected':''}>PM</option></select>`}
makeTimePicker('fromTime',9,0,'AM');makeTimePicker('toTime',8,0,'PM');makeTimePicker('fixedTime',6,0,'PM');
function pickerMinutes(id){const e=$('#'+id),h=+e.querySelector('.h').value,m=+e.querySelector('.m').value,ap=e.querySelector('.ap').value;return((h%12)+(ap==='PM'?12:0))*60+m}
function dateAt(dateStr,mins){const [y,mo,d]=dateStr.split('-').map(Number),h=Math.floor(mins/60),m=mins%60;return new Date(y,mo-1,d,h,m,0,0)}
function burstOffset(i){return(Math.floor(i/5)*100+(i%5)*10)*60000}
function randomInt(min,max){return Math.floor(min+Math.random()*(max-min+1))}
function matchFiles(list){const videos=[],caps=new Map();for(const f of list){const n=f.name,lower=n.toLowerCase();if(lower.endsWith('.mp4')||lower.endsWith('.mov')||String(f.type||'').startsWith('video/'))videos.push(f);else if(lower.endsWith('.json'))continue;else if(/_caption(\.txt)?$/i.test(n)){const base=n.replace(/\.txt$/i,'').replace(/_caption$/i,'');caps.set(base,f);caps.set(base.toLowerCase(),f)}}return{videos,caps}}
function videoBase(name){return name.replace(/\.(mp4|mov)$/i,'')}
function setPickedFiles(files,label='Files'){state.pickedFiles=[...files];const {videos,caps}=matchFiles(state.pickedFiles);const uniqueCaps=new Set([...caps.values()]);$('#fileCount').textContent=`${videos.length} video(s) · ${uniqueCaps.size} caption file(s) · ${label}`}
$('#files').onchange=()=>setPickedFiles($('#files').files,'manual selection');
$('#folderFiles').onchange=()=>setPickedFiles($('#folderFiles').files,'folder selected');
async function buildPicked(){const {videos,caps}=matchFiles(state.pickedFiles);if(videos.length>100)throw new Error('Maximum 100 videos per batch.');const fallback=$('#fallbackCaption').value,out=[];for(const v of videos){const base=videoBase(v.name),cf=caps.get(base)||caps.get(base.toLowerCase());let caption=fallback;if(cf instanceof File)caption=await cf.text();out.push({name:v.name,type:v.type||'video/mp4',blob:v,caption:String(caption||'').slice(0,2200)})}return out}
function selectedAccountIds(){return[...state.selected].filter(id=>state.accounts.some(a=>a.id===id)).slice(0,15)}
function computeTimes(videoCount,accountIds){const date=$('#scheduleDate').value;if(!date)throw new Error('Date select karo.');const now=Date.now(),dayStart=dateAt(date,0).getTime(),dayEnd=dateAt(date,1439).getTime(),starts={};if(dayEnd<now-90000)throw new Error('Selected date past me hai.');if(state.mode==='fixed'){let t=dateAt(date,pickerMinutes('fixedTime')).getTime();if(t<now-90000)throw new Error('Fixed time past me hai.');if(t<=now+5000)t=now;accountIds.forEach(id=>starts[id]=t)}else{let from=state.mode==='24h'?0:pickerMinutes('fromTime'),to=state.mode==='24h'?1439:pickerMinutes('toTime');if(to<=from)throw new Error('To time, From ke baad hona chahiye.');accountIds.forEach(id=>{let min=from;if(dayStart<=now&&now<=dayEnd)min=Math.max(min,Math.ceil((now-dayStart)/60000));if(min>to)throw new Error('Selected time window already ended.');starts[id]=dateAt(date,randomInt(min,to)).getTime()})}return Array.from({length:videoCount},(_,i)=>Object.fromEntries(accountIds.map(id=>[id,new Date(starts[id]+burstOffset(i)).toISOString()]))) }

async function saveBatchAndUpload(){if(state.uploading){toast('Upload already running.');return}try{const accountIds=selectedAccountIds();if(!accountIds.length)throw new Error('Kam se kam 1 account select karo.');const files=await buildPicked();if(!files.length)throw new Error('Video files select karo.');if(state.storage&&state.storage.safeToSchedule===false)throw new Error('Backend storage is not safe for scheduling yet.');const times=computeTimes(files.length,accountIds),id=crypto.randomUUID();const rec={id,createdAt:new Date().toISOString(),backend:state.backend,accountIds,files:files.map((f,i)=>({...f,times:times[i]})),nextIndex:0,status:'pending'};$('#uploadProgressWrap').style.display='block';$('#uploadProgressText').textContent='Saving files safely on this phone…';await dbPut(rec);state.lastUploadError='';toast(`${files.length} videos saved to resume queue`);state.pickedFiles=[];$('#files').value='';$('#folderFiles').value='';$('#fileCount').textContent='Files saved. Uploading to backend…';await renderUploadMini();resumeUploads()}catch(e){toast(e.message)}}
async function resumeUploads(){if(state.uploading||!state.backend)return;const all=(await dbAll()).filter(b=>b.backend===state.backend&&b.status!=='done');if(!all.length){renderUploadMini();return}state.uploading=true;try{for(const batch of all){while(batch.nextIndex<batch.files.length){const chunk=batch.files.slice(batch.nextIndex,batch.nextIndex+5),form=new FormData();chunk.forEach(f=>form.append('videos',f.blob,f.name));const explicit=[];for(const f of chunk)for(const aid of batch.accountIds)explicit.push(f.times[aid]);form.append('config',JSON.stringify({accountIds:batch.accountIds,mode:'explicit',explicitTimes:explicit,captions:chunk.map(f=>f.caption),batchId:batch.id}));$('#uploadProgressWrap').style.display='block';const pct=Math.round(batch.nextIndex/batch.files.length*100);$('#uploadProgress').style.width=pct+'%';$('#uploadProgressText').textContent=`Uploading ${batch.nextIndex}/${batch.files.length} videos…`;await api('/api/schedule',{method:'POST',body:form});batch.nextIndex+=chunk.length;await dbPut(batch);state.lastUploadError='';await renderUploadMini();await refreshJobsOnly()}batch.status='done';await dbDelete(batch.id);$('#uploadProgress').style.width='100%';$('#uploadProgressText').textContent='All selected videos uploaded & scheduled.';toast('All videos scheduled ✅')}}catch(e){state.lastUploadError=e.message;toast('Upload paused: '+e.message)}finally{state.uploading=false;await renderUploadMini();setTimeout(()=>{if(!state.uploading)resumeUploads()},15000)}}
async function clearPendingUploads(){const all=(await dbAll()).filter(b=>b.backend===state.backend&&b.status!=='done');if(!all.length){toast('No pending uploads.');return}if(!confirm(`Clear ${all.reduce((n,b)=>n+(b.files.length-b.nextIndex),0)} waiting video(s) from this phone? Backend jobs already created will stay.`))return;for(const b of all)await dbDelete(b.id);state.lastUploadError='';$('#uploadProgressWrap').style.display='none';await renderUploadMini();toast('Pending upload queue cleared')}
async function refreshJobsOnly(){try{state.jobs=await api('/api/jobs');renderStats();renderQueue();renderPublished();renderNext()}catch{}}
async function renderUploadMini(){const el=$('#uploadQueueMini'),all=(await dbAll()).filter(b=>b.backend===state.backend&&b.status!=='done'),pending=all.reduce((n,b)=>n+(b.files.length-b.nextIndex),0);$('#pendingUploads').textContent=`${pending} pending`;if(!all.length){el.className='empty';el.textContent='No pending uploads.';return}el.className='';el.innerHTML=(state.lastUploadError?`<div class="uploaderror">Last error: ${esc(state.lastUploadError)}</div>`:'')+all.map(b=>`<div class="job"><div class="jobname">${b.files.length-b.nextIndex} of ${b.files.length} videos pending</div><div class="jobmeta">Saved ${fmt(b.createdAt)} · resumes when this app is open</div></div>`).join('')}

function setMode(mode){state.mode=mode;$('#modeRandom').classList.toggle('active',mode==='random');$('#mode24').classList.toggle('active',mode==='24h');$('#modeFixed').classList.toggle('active',mode==='fixed');$('#randomTimes').style.display=mode==='random'?'grid':'none';$('#fixedTimes').style.display=mode==='fixed'?'block':'none';$('#mode24Note').style.display=mode==='24h'?'block':'none'}
$('#scheduleBtn').onclick=saveBatchAndUpload;
$('#modeRandom').onclick=()=>setMode('random');$('#mode24').onclick=()=>setMode('24h');$('#modeFixed').onclick=()=>setMode('fixed');
$('#selectAllAccounts').onclick=()=>{state.accounts.slice(0,15).forEach(a=>state.selected.add(a.id));saveSelection();renderChips()};$('#clearAccounts').onclick=()=>{state.selected.clear();saveSelection();renderChips()};
$('#queueSearch').oninput=renderQueue;$('#queueFilter').onchange=renderQueue;$('#retryFailed').onclick=async()=>{try{const r=await api('/api/jobs/retry-failed',{method:'POST'});toast(`${r.retried||0} failed jobs queued`);refreshAll(false)}catch(e){toast(e.message)}};$('#refreshPublished').onclick=()=>refreshAll(false);$('#refreshQueue').onclick=()=>refreshAll(false);$('#deleteFailed').onclick=deleteAllFailed;$('#refreshAccounts').onclick=()=>refreshAll(false);
$('#retryPendingBtn').onclick=()=>{state.lastUploadError='';resumeUploads()};$('#clearPendingBtn').onclick=clearPendingUploads;
$('#refreshAllBtn').onclick=()=>refreshAll();$('#storageRefreshBtn').onclick=()=>refreshSystem();
$('#driveConnectBtn').onclick=()=>{if(!state.backend){toast('Backend URL save karo.');return}window.open(state.backend+'/api/google-drive/connect','_blank','noopener');toast('Google Drive authorization opened. Return here and tap Refresh Status.')};
$('#driveTestBtn').onclick=async()=>{try{const r=await api('/api/drive-test');toast(r.uploadedAndDeleted?'Drive upload + delete test passed ✅':'Drive test completed');await refreshSystem()}catch(e){toast('Drive test: '+e.message)}};

$('#connectAccount').onclick=async()=>{const label=$('#accLabel').value.trim(),igUserId=$('#accIgId').value.trim(),accessToken=$('#accToken').value.trim();if(!label||!igUserId||!accessToken){toast('Saare account fields fill karo.');return}try{const r=await api('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label,igUserId,accessToken})});if(r.backupBlob){const raw=localStorage.getItem(backupKey()),arr=raw?JSON.parse(raw):[];arr.push(r.backupBlob);localStorage.setItem(backupKey(),JSON.stringify([...new Set(arr)]))}$('#accToken').value='';state.selected.add(r.id);saveSelection();toast('Account connected');await refreshAll(false)}catch(e){toast(e.message)}};
$('#saveBackend').onclick=async()=>{const u=cleanUrl($('#backendUrl').value);if(!/^https:\/\//i.test(u)){toast('HTTPS backend URL dalo.');return}state.backend=u;localStorage.setItem('iap_backend_url',u);loadSelection();await refreshAll()};

function initDate(){const d=new Date();$('#scheduleDate').value=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
async function init(){initDate();setMode('random');state.backend=cleanUrl(localStorage.getItem('iap_backend_url')||'https://insta-auto-publisher-backend.onrender.com');$('#backendUrl').value=state.backend;loadSelection();if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{})}await renderUploadMini();await refreshAll(false);setInterval(()=>refreshJobsOnly(),10000);setInterval(()=>refreshSystem(),60000)}
init();
