const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={backend:'',accounts:[],jobs:[],counts:null,selected:new Set(),mode:'random',pickedFiles:[],uploading:false,lastUploadError:'',health:null,storage:null,drive:null,scheduler:null,publishedAll:[],publishedSummary:null,publishedLoadedAt:0,publishedAccount:'all'};
const NORMAL_MAX_VIDEOS=100, MONTHLY_MAX_VIDEOS=1860;
const ACTIVE=new Set(['scheduled','processing','ready','publishing','retry_wait']);
// Keep the old DB name so pending uploads from v12 survive this upgrade.
const DB_NAME='iap_mobile_v12', STORE='uploadBatches';

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3000)}
function cleanUrl(v){return String(v||'').trim().replace(/\/+$/,'')}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(d){try{return new Date(d).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}catch{return d||''}}
function statusClass(s){return ['published','failed','retry_wait'].includes(s)?s:''}
async function api(path,opts={}){if(!state.backend)throw new Error('Backend URL save karo.');const r=await fetch(state.backend+path,opts);let j={};const txt=await r.text();try{j=txt?JSON.parse(txt):{}}catch{j={error:txt||`HTTP ${r.status}`}}if(!r.ok)throw new Error(j.error||j.message||`HTTP ${r.status}`);return j}

function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(['queue','accounts'].includes(name))refreshAll(false);if(name==='published')refreshPublishedExact(false)}
$$('.navbtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function setServer(ok){const p=$('#serverPill');p.textContent=ok?'Server online':'Server offline';p.className='pill '+(ok?'online':'offline')}

function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE,{keyPath:'id'})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbPut(v){const db=await openDb();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(v);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function dbDelete(id){const db=await openDb();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).delete(id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function dbAll(){const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}

function backupKey(){return 'iap_recovery_'+btoa(state.backend).replace(/=/g,'')}
function selKey(){return 'iap_selected_'+btoa(state.backend).replace(/=/g,'')}
async function mirrorRecovery(){if(!state.backend)return;try{const pack=await api('/api/accounts/recovery-pack');if(pack.backups?.length)localStorage.setItem(backupKey(),JSON.stringify(pack.backups.map(x=>x.backupBlob)))}catch{}}
async function tryRestore(){if(!state.backend)return[];try{let accts=await api('/api/accounts');if(accts.length){await mirrorRecovery();return accts}const raw=localStorage.getItem(backupKey());const backups=raw?JSON.parse(raw):[];if(backups.length){await api('/api/accounts/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backups})});accts=await api('/api/accounts');if(accts.length)toast(`Recovered ${accts.length} account(s)`)}return accts}catch{return[]}}
function loadSelection(){try{state.selected=new Set(JSON.parse(localStorage.getItem(selKey())||'[]'))}catch{state.selected=new Set()}}
function saveSelection(){localStorage.setItem(selKey(),JSON.stringify([...state.selected]))}

async function refreshSystem(){if(!state.backend)return;try{state.health=await api('/api/health')}catch{state.health=null}try{state.storage=await api('/api/storage-status')}catch{state.storage=null}try{state.drive=await api('/api/google-drive/connect-info')}catch{state.drive=null}try{state.scheduler=await api('/api/scheduler/status')}catch{state.scheduler=null}renderSystem();renderScheduler()}
async function refreshAll(showErr=true){if(!state.backend){setServer(false);return}try{state.health=await api('/api/health');setServer(true);state.accounts=await tryRestore();loadSelection();state.selected=new Set([...state.selected].filter(id=>state.accounts.some(a=>a.id===id)));try{const dash=await api('/api/dashboard-state');state.jobs=Array.isArray(dash.jobs)?dash.jobs:[];state.counts=dash.counts||null}catch{state.jobs=await api('/api/jobs');state.counts=null}try{state.storage=await api('/api/storage-status')}catch{}try{state.drive=await api('/api/google-drive/connect-info')}catch{}try{state.scheduler=await api('/api/scheduler/status')}catch{}render();await mirrorRecovery();resumeUploads()}catch(e){setServer(false);if(showErr)toast(e.message)}}
function render(){renderStats();renderAccounts();renderChips();renderQueue();renderPublished();renderNext();renderUploadMini();renderSystem();renderScheduler()}

function renderStats(){const active=state.counts?.active??state.jobs.filter(j=>ACTIVE.has(j.status)).length;$('#statAccounts').textContent=state.accounts.length;$('#statScheduled').textContent=active;$('#statPublished').textContent=state.counts?.published??state.jobs.filter(j=>j.status==='published').length;$('#statFailed').textContent=state.counts?.failed??state.jobs.filter(j=>j.status==='failed').length}
function renderSystem(){const st=state.storage, dr=state.drive, h=state.health;$('#backendVersion').textContent=h?`Backend v${h.version||'?'} · ${h.mediaStorage||st?.media||'?'}`:'Backend status unavailable';$('#stateStorage').textContent=st?.state||'—';$('#mediaStorage').textContent=st?.media||'—';$('#restartSafe').textContent=st?String(!!st.restartSafe):'—';$('#driveConnected').textContent=dr?String(!!dr.connected):'—';const p=$('#storagePill');const safe=!!st?.safeToSchedule;p.textContent=safe?'Storage safe':'Storage check';p.className='pill '+(safe?'online':'offline');let msg='';if(st?.exactTimingWarning)msg=st.exactTimingWarning;else if(st?.reasons?.length)msg=st.reasons.join(' ');else if(safe)msg='Postgres + durable media are ready for bulk scheduling.';$('#storageMessage').textContent=msg}
function renderScheduler(){const x=state.scheduler,p=$('#schedulerPillMobile'),d=$('#schedulerDetailMobile');if(!p||!d)return;if(!x){p.textContent='Unavailable';p.className='pill offline';d.textContent='Backend scheduler status unavailable.';return}const paused=!!x.paused;p.textContent=paused?'Paused':'Active';p.className='pill '+(paused?'offline':'online');d.textContent=paused?`All posting paused · ${x.activeJobs||0} active job(s) preserved.`:`Catch-up protection ON · ${x.activeJobs||0} active · ${x.overdueJobs||0} overdue`;$('#pauseAllMobile').disabled=paused;$('#resumeAllMobile').disabled=!paused}
function renderChips(){populatePublishedAccountFilter();const el=$('#accountChips');if(!state.accounts.length){el.innerHTML='<span class="sub">No connected accounts.</span>';updateMonthlySummary();return}el.innerHTML=state.accounts.map(a=>`<label class="chip"><input type="checkbox" data-acct="${a.id}" ${state.selected.has(a.id)?'checked':''}>@${esc(a.label)}</label>`).join('');el.querySelectorAll('input').forEach(i=>i.onchange=()=>{i.checked?state.selected.add(i.dataset.acct):state.selected.delete(i.dataset.acct);saveSelection();updateMonthlySummary()});updateMonthlySummary()}
function renderAccounts(){const el=$('#accountsList');if(!state.accounts.length){el.innerHTML='<div class="empty">No connected accounts.</div>';return}el.innerHTML=state.accounts.map(a=>`<div class="accountrow"><div class="grow"><strong>@${esc(a.label)}</strong><span>${esc(a.igUserId)}</span></div><button class="btn small red" data-removeacct="${a.id}">Remove</button></div>`).join('');el.querySelectorAll('[data-removeacct]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this account?'))return;try{await api('/api/accounts/'+b.dataset.removeacct,{method:'DELETE'});state.selected.delete(b.dataset.removeacct);saveSelection();await refreshAll()}catch(e){toast(e.message)}})}

function renderQueue(){const el=$('#queueList');if(!el)return;const q=$('#queueSearch').value.trim().toLowerCase(),f=$('#queueFilter').value;let jobs=state.jobs.filter(j=>j.status!=='published');if(f==='active')jobs=jobs.filter(j=>ACTIVE.has(j.status));else if(f!=='all')jobs=jobs.filter(j=>j.status===f);if(q)jobs=jobs.filter(j=>(String(j.fileName||'')+' '+String(j.accountLabel||'')).toLowerCase().includes(q));jobs.sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));if(!jobs.length){el.innerHTML='<div class="empty">No matching jobs.</div>';return}el.innerHTML=jobs.slice(0,500).map(j=>`<div class="job"><div class="jobtop"><div class="grow"><div class="jobname">${esc(j.fileName)}</div><div class="jobmeta">@${esc(j.accountLabel)} · ${fmt(j.scheduledAt)}</div>${j.error?`<div class="jobmeta errtxt">${esc(j.error)}</div>`:''}</div><span class="status ${statusClass(j.status)}">${esc(j.status)}</span></div><div class="jobactions">${!['processing','publishing','published'].includes(j.status)?`<button class="btn small purple" data-now="${j.id}">⚡ Post Now</button>`:''}${!['processing','publishing','published'].includes(j.status)?`<button class="btn small red" data-del="${j.id}">🗑 Delete</button>`:''}${j.status==='failed'?`<button class="btn small ghost" data-retry="${j.id}">↻ Retry</button>`:''}</div></div>`).join('');el.querySelectorAll('[data-now]').forEach(b=>b.onclick=()=>jobAction(b.dataset.now,'post-now'));el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteJob(b.dataset.del));el.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>jobAction(b.dataset.retry,'retry'))}
async function jobAction(id,act){try{await api(`/api/jobs/${id}/${act}`,{method:'POST'});toast(act==='post-now'?'Moved to Post Now queue':'Retry queued');await refreshAll(false)}catch(e){toast(e.message)}}
async function deleteJob(id){if(!confirm('Delete this scheduled job?'))return;try{await api('/api/jobs/'+id,{method:'DELETE'});toast('Deleted');await refreshAll(false)}catch(e){toast(e.message)}}
async function deleteAllFailed(){const failed=state.jobs.filter(j=>j.status==='failed');if(!failed.length){toast('No failed jobs.');return}if(!confirm(`Delete ${failed.length} failed jobs?`))return;let n=0;for(const j of failed){try{await api('/api/jobs/'+j.id,{method:'DELETE'});n++}catch{}}toast(`Deleted ${n} failed jobs`);await refreshAll(false)}
function localDayKey(v){const d=new Date(v);return Number.isFinite(d.getTime())?dateKey(d):''}
function populatePublishedAccountFilter(){
  const el=$('#publishedAccountFilter');if(!el)return;
  const keep=state.publishedAccount||'all';
  el.innerHTML='<option value="all">All accounts</option>'+state.accounts.map(a=>`<option value="${esc(a.id)}">@${esc(a.label)}</option>`).join('');
  el.value=[...el.options].some(o=>o.value===keep)?keep:'all';state.publishedAccount=el.value;
}
async function loadPublishedAll(force=false){
  if(!force&&state.publishedLoadedAt&&Date.now()-state.publishedLoadedAt<120000)return state.publishedAll;
  try{const summary=await api(`/api/published-stats?tzOffsetMinutes=${-new Date().getTimezoneOffset()}`);if(summary?.ok){state.publishedSummary=summary;state.publishedLoadedAt=Date.now();return state.publishedAll}}catch{}
  try{const all=await api('/api/jobs');if(Array.isArray(all)){state.publishedAll=all;state.publishedSummary=null;state.publishedLoadedAt=Date.now()}}catch{if(!state.publishedAll.length)state.publishedAll=state.jobs.slice()}
  return state.publishedAll;
}
function renderPublished(){
  const el=$('#publishedList');if(!el)return;
  const source=state.publishedAll.length?state.publishedAll:state.jobs;
  const aid=state.publishedAccount||'all';
  const jobs=source.filter(j=>j.status==='published'&&(aid==='all'||String(j.accountId)===aid)).sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0));
  if(state.publishedSummary?.accounts){
    const rows=aid==='all'?state.publishedSummary.accounts:state.publishedSummary.accounts.filter(r=>String(r.accountId)===aid);
    const firstDates=rows.map(r=>r.firstPublishedAt).filter(Boolean).sort((a,b)=>new Date(a)-new Date(b));
    if($('#publishedTodayCount'))$('#publishedTodayCount').textContent=String(rows.reduce((n,r)=>n+Number(r.today||0),0));
    if($('#publishedTotalCount'))$('#publishedTotalCount').textContent=String(rows.reduce((n,r)=>n+Number(r.total||0),0));
    if($('#publishedSince'))$('#publishedSince').textContent=firstDates.length?new Date(firstDates[0]).toLocaleDateString():'—';
  }else{
    const today=dateKey(new Date()),todayCount=jobs.filter(j=>localDayKey(j.publishedAt||j.scheduledAt)===today).length;
    const first=jobs.slice().sort((a,b)=>new Date(a.publishedAt||a.scheduledAt)-new Date(b.publishedAt||b.scheduledAt))[0];
    if($('#publishedTodayCount'))$('#publishedTodayCount').textContent=String(todayCount);
    if($('#publishedTotalCount'))$('#publishedTotalCount').textContent=String(jobs.length);
    if($('#publishedSince'))$('#publishedSince').textContent=first?new Date(first.publishedAt||first.scheduledAt).toLocaleDateString():'—';
  }
  if(!jobs.length){el.innerHTML='<div class="empty">No published posts for this account/filter yet.</div>';return}
  el.innerHTML=jobs.slice(0,400).map(j=>`<div class="job pub"><div class="pubicon">🎬</div><div class="grow"><div class="jobname">${esc(j.fileName)}</div><div class="jobmeta">@${esc(j.accountLabel)} · ${fmt(j.publishedAt||j.scheduledAt)}</div><div class="jobactions">${j.permalink?`<a class="btn small green" target="_blank" rel="noopener" href="${esc(j.permalink)}">View on Instagram ↗</a>`:'<span class="tiny">Permalink pending…</span>'}</div></div></div>`).join('')
}
async function refreshPublishedExact(force=true){await loadPublishedAll(force);populatePublishedAccountFilter();renderPublished();await refreshGrowthAnalytics()}
async function refreshGrowthAnalytics(){
  const el=$('#growthStatus'),aid=state.publishedAccount||'all';if(!el)return;
  if(aid==='all'){el.textContent='Select one account to see follower growth.';return}
  el.textContent='Refreshing Instagram growth…';
  try{
    const x=await api(`/api/account-analytics?accountId=${encodeURIComponent(aid)}&tzOffsetMinutes=${-new Date().getTimezoneOffset()}`);
    const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
    const cur=Number.isFinite(Number(x.currentFollowers))?Number(x.currentFollowers):null;
    const gain=Number.isFinite(Number(x.followersGain))?Number(x.followersGain):null;
    const baseline=Number.isFinite(Number(x.baselineFollowers))?Number(x.baselineFollowers):null;
    const mediaCount=Number.isFinite(Number(x.currentMediaCount))?Number(x.currentMediaCount):null;
    set('#followersCurrent',cur===null?'—':cur.toLocaleString());
    set('#followersGain',gain===null?'—':`${gain>=0?'+':''}${gain.toLocaleString()}`);
    set('#followersBaseline',baseline===null?'—':baseline.toLocaleString());
    set('#trackingSince',x.baselineAt?new Date(x.baselineAt).toLocaleDateString():'—');
    set('#reachToday',Number.isFinite(Number(x.reachToday))?Number(x.reachToday).toLocaleString():'—');
    set('#profileViewsToday',Number.isFinite(Number(x.profileViewsToday))?Number(x.profileViewsToday).toLocaleString():'—');
    set('#mediaCountCurrent',mediaCount===null?'—':mediaCount.toLocaleString());
    const source=x.baselineSource?` · baseline: ${x.baselineSource}`:'';
    el.textContent=(x.note||'Growth refreshed.')+source;
  }catch(e){el.textContent=/404|Cannot GET/i.test(String(e.message))?'Follower analytics backend update is not deployed yet.':e.message}
}

let nextJob=null;
function renderNext(){const now=Date.now();const arr=state.jobs.filter(j=>ACTIVE.has(j.status)&&new Date(j.scheduledAt).getTime()>=now-60000).sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));nextJob=arr[0]||null;$('#nextPostMeta').textContent=nextJob?`@${nextJob.accountLabel} · ${nextJob.fileName}`:'No scheduled job';updateCountdown()}
function updateCountdown(){if(!nextJob){$('#countdown').textContent='--:--';return}let s=Math.max(0,Math.floor((new Date(nextJob.scheduledAt)-Date.now())/1000));const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),sec=s%60;$('#countdown').textContent=(h?`${h}h `:'')+`${String(m).padStart(2,'0')}m ${String(sec).padStart(2,'0')}s`}
setInterval(updateCountdown,1000);

function makeTimePicker(id,h=9,m=0,ap='AM'){const el=$('#'+id);const hs=Array.from({length:12},(_,i)=>i+1).map(v=>`<option ${v===h?'selected':''}>${v}</option>`).join('');const ms=Array.from({length:60},(_,i)=>i).map(v=>`<option value="${v}" ${v===m?'selected':''}>${String(v).padStart(2,'0')}</option>`).join('');el.innerHTML=`<select class="select h">${hs}</select><b>:</b><select class="select m">${ms}</select><select class="select ap"><option ${ap==='AM'?'selected':''}>AM</option><option ${ap==='PM'?'selected':''}>PM</option></select>`}
makeTimePicker('fromTime',9,0,'AM');makeTimePicker('toTime',8,0,'PM');makeTimePicker('fixedTime',6,0,'PM');
function pickerMinutes(id){const e=$('#'+id),h=+e.querySelector('.h').value,m=+e.querySelector('.m').value,ap=e.querySelector('.ap').value;return((h%12)+(ap==='PM'?12:0))*60+m}
function dateAt(dateStr,mins){const [y,mo,d]=dateStr.split('-').map(Number),h=Math.floor(mins/60),m=mins%60;return new Date(y,mo-1,d,h,m,0,0)}
function burstOffset(i){return(Math.floor(i/5)*100+(i%5)*10)*60000}
function randomInt(min,max){return Math.floor(min+Math.random()*(max-min+1))}
function dateKey(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function parseDateOnly(s){const d=new Date(`${s}T00:00:00`);return Number.isFinite(d.getTime())?d:null}
function addDaysKey(s,n){const d=parseDateOnly(s);if(!d)return null;d.setDate(d.getDate()+n);return dateKey(d)}
function inclusiveDayCount(start,end){const a=parseDateOnly(start),b=parseDateOnly(end);if(!a||!b)return 0;return Math.floor((new Date(b.getFullYear(),b.getMonth(),b.getDate())-new Date(a.getFullYear(),a.getMonth(),a.getDate()))/86400000)+1}
function monthlyPlanSpec(){const start=$('#monthlyStart')?.value||'',end=$('#monthlyEnd')?.value||'',daily=Math.max(1,Math.min(60,Number($('#monthlyDaily')?.value||50))),days=inclusiveDayCount(start,end);return {start,end,daily,days,required:days>0?days*daily:0}}
function updateMonthlySummary(){const el=$('#monthlySummary');if(!el)return;const p=monthlyPlanSpec(),videos=matchFiles(state.pickedFiles).videos.length,accounts=selectedAccountIds().length;if(p.days<1){el.className='summary warn';el.textContent='Choose a valid start/end date.';return}const missing=Math.max(0,p.required-videos),jobs=p.required*accounts;el.className='summary '+(missing?'warn':'good');el.textContent=`${p.days} day(s) × ${p.daily} = ${p.required} videos needed · ${accounts} account(s) = ${jobs} jobs${missing?` · ${missing} more video(s) needed`:' · ready'}`}
function computeMonthlyTimes(accountIds,p){const times=[],now=Date.now(),today=dateKey(new Date());for(let v=0;v<p.required;v++){const dayIndex=Math.floor(v/p.daily),slot=v%p.daily,ds=addDaysKey(p.start,dayIndex),dayStart=new Date(`${ds}T00:00:00`).getTime();let startMin=5,endMin=1435;if(ds===today)startMin=Math.max(startMin,Math.ceil((now-dayStart)/60000)+5);if(startMin>=endMin)throw new Error('Today is almost over. Choose tomorrow as Monthly Smart start date.');const interval=(endMin-startMin)/p.daily,row={};for(let a=0;a<accountIds.length;a++){const rotated=(a+dayIndex)%accountIds.length,offset=(interval/accountIds.length)*rotated,minute=startMin+slot*interval+offset;row[accountIds[a]]=new Date(dayStart+Math.floor(minute*60000)).toISOString()}times.push(row)}return times}
function matchFiles(list){const videos=[],caps=new Map();for(const f of list){const n=f.name,lower=n.toLowerCase();if(lower.endsWith('.mp4')||lower.endsWith('.mov')||String(f.type||'').startsWith('video/'))videos.push(f);else if(lower.endsWith('.json'))continue;else if(/_caption(\.txt)?$/i.test(n)){const base=n.replace(/\.txt$/i,'').replace(/_caption$/i,'');caps.set(base,f);caps.set(base.toLowerCase(),f)}}return{videos,caps}}
function videoBase(name){return name.replace(/\.(mp4|mov)$/i,'')}
function pickedKey(f){return [String(f.webkitRelativePath||''),String(f.name||'').toLowerCase(),Number(f.size||0),Number(f.lastModified||0)].join('|')}
function setPickedFiles(files,label='Files'){
  const existing=new Set(state.pickedFiles.map(pickedKey));let added=0;
  for(const f of [...files]){const k=pickedKey(f);if(!existing.has(k)){state.pickedFiles.push(f);existing.add(k);added++}}
  const {videos,caps}=matchFiles(state.pickedFiles),uniqueCaps=new Set([...caps.values()]);
  $('#fileCount').textContent=`${videos.length} video(s) · ${uniqueCaps.size} caption file(s) selected · ${added} new from ${label}`;
  $('#files').value='';$('#folderFiles').value='';updateMonthlySummary();toast(`${added} new file(s) added · previous selection kept`)
}
$('#files').onchange=()=>setPickedFiles($('#files').files,'manual selection');
$('#folderFiles').onchange=()=>setPickedFiles($('#folderFiles').files,'folder');
async function buildPicked(){const {videos,caps}=matchFiles(state.pickedFiles);if(videos.length>MONTHLY_MAX_VIDEOS)throw new Error(`Maximum ${MONTHLY_MAX_VIDEOS} videos in Monthly Smart mode.`);const fallback=$('#fallbackCaption').value,out=[];for(const v of videos){const base=videoBase(v.name),cf=caps.get(base)||caps.get(base.toLowerCase());let caption=fallback;if(cf instanceof File)caption=await cf.text();out.push({name:v.name,type:v.type||'video/mp4',blob:v,caption:String(caption||'').slice(0,2200)})}return out}
function selectedAccountIds(){return[...state.selected].filter(id=>state.accounts.some(a=>a.id===id)).slice(0,15)}
function computeTimes(videoCount,accountIds){const date=$('#scheduleDate').value;if(!date)throw new Error('Date select karo.');const now=Date.now(),dayStart=dateAt(date,0).getTime(),dayEnd=dateAt(date,1439).getTime(),starts={};if(dayEnd<now-90000)throw new Error('Selected date past me hai.');if(state.mode==='fixed'){let t=dateAt(date,pickerMinutes('fixedTime')).getTime();if(t<now-90000)throw new Error('Fixed time past me hai.');if(t<=now+5000)t=now;accountIds.forEach(id=>starts[id]=t)}else{let from=state.mode==='24h'?0:pickerMinutes('fromTime'),to=state.mode==='24h'?1439:pickerMinutes('toTime');if(to<=from)throw new Error('To time, From ke baad hona chahiye.');accountIds.forEach(id=>{let min=from;if(dayStart<=now&&now<=dayEnd)min=Math.max(min,Math.ceil((now-dayStart)/60000));if(min>to)throw new Error('Selected time window already ended.');starts[id]=dateAt(date,randomInt(min,to)).getTime()})}return Array.from({length:videoCount},(_,i)=>Object.fromEntries(accountIds.map(id=>[id,new Date(starts[id]+burstOffset(i)).toISOString()]))) }

async function saveBatchAndUpload(){try{const accountIds=selectedAccountIds();if(!accountIds.length)throw new Error('Kam se kam 1 account select karo.');let files=await buildPicked();if(!files.length)throw new Error('Video files select karo.');if(state.storage&&state.storage.safeToSchedule===false)throw new Error('Backend storage is not safe for scheduling yet.');let times,extraConfig={scheduleKind:state.mode};if(state.mode==='monthly'){const p=monthlyPlanSpec();if(p.days<1)throw new Error('Monthly dates select karo.');if(files.length<p.required)throw new Error(`Monthly plan needs ${p.required} videos. Select ${p.required-files.length} more.`);if(files.length>p.required){files=files.slice(0,p.required);toast(`Using first ${p.required} videos for this monthly plan.`)}times=computeMonthlyTimes(accountIds,p);extraConfig={scheduleKind:'monthly_smart',planId:crypto.randomUUID(),monthlyPlan:{startDate:p.start,endDate:p.end,dailyLimit:p.daily,distribution:'smart_24h_staggered',videos:p.required,accounts:accountIds.length}}}else{if(files.length>NORMAL_MAX_VIDEOS)throw new Error(`Normal modes allow max ${NORMAL_MAX_VIDEOS} videos. Use Monthly Smart for larger batches.`);times=computeTimes(files.length,accountIds)}const id=crypto.randomUUID();const rec={id,createdAt:new Date().toISOString(),backend:state.backend,accountIds,files:files.map((f,i)=>({...f,times:times[i]})),extraConfig,nextIndex:0,status:'pending'};$('#uploadProgressWrap').style.display='block';$('#uploadProgressText').textContent='Saving files safely on this phone…';await dbPut(rec);state.lastUploadError='';toast(`${files.length} videos added to resume queue · existing background uploads keep running`);state.pickedFiles=[];$('#files').value='';$('#folderFiles').value='';$('#fileCount').textContent='Files saved. Uploading to backend…';updateMonthlySummary();await renderUploadMini();resumeUploads()}catch(e){toast(e.message)}}
async function resumeUploads(){if(state.uploading||!state.backend)return;const all=(await dbAll()).filter(b=>b.backend===state.backend&&b.status!=='done');if(!all.length){renderUploadMini();return}state.uploading=true;try{for(const batch of all){while(batch.nextIndex<batch.files.length){const chunk=batch.files.slice(batch.nextIndex,batch.nextIndex+5),form=new FormData();chunk.forEach(f=>form.append('videos',f.blob,f.name));const explicit=[];for(const f of chunk)for(const aid of batch.accountIds)explicit.push(f.times[aid]);form.append('config',JSON.stringify({accountIds:batch.accountIds,mode:'explicit',explicitTimes:explicit,captions:chunk.map(f=>f.caption),batchId:batch.id,...(batch.extraConfig||{})}));$('#uploadProgressWrap').style.display='block';const pct=Math.round(batch.nextIndex/batch.files.length*100);$('#uploadProgress').style.width=pct+'%';$('#uploadProgressText').textContent=`Uploading ${batch.nextIndex}/${batch.files.length} videos…`;await api('/api/schedule',{method:'POST',body:form});batch.nextIndex+=chunk.length;await dbPut(batch);state.lastUploadError='';await renderUploadMini();await refreshJobsOnly()}batch.status='done';await dbDelete(batch.id);$('#uploadProgress').style.width='100%';$('#uploadProgressText').textContent='All selected videos uploaded & scheduled.';toast('All videos scheduled ✅')}}catch(e){state.lastUploadError=e.message;toast('Upload paused: '+e.message)}finally{state.uploading=false;await renderUploadMini();setTimeout(()=>{if(!state.uploading)resumeUploads()},15000)}}
async function clearPendingUploads(){const all=(await dbAll()).filter(b=>b.backend===state.backend&&b.status!=='done');if(!all.length){toast('No pending uploads.');return}if(!confirm(`Clear ${all.reduce((n,b)=>n+(b.files.length-b.nextIndex),0)} waiting video(s) from this phone? Backend jobs already created will stay.`))return;for(const b of all)await dbDelete(b.id);state.lastUploadError='';$('#uploadProgressWrap').style.display='none';await renderUploadMini();toast('Pending upload queue cleared')}
async function refreshJobsOnly(){try{try{const dash=await api('/api/dashboard-state');state.jobs=Array.isArray(dash.jobs)?dash.jobs:[];state.counts=dash.counts||null}catch{state.jobs=await api('/api/jobs');state.counts=null}renderStats();renderQueue();renderPublished();renderNext()}catch{}}
async function renderUploadMini(){const el=$('#uploadQueueMini'),all=(await dbAll()).filter(b=>b.backend===state.backend&&b.status!=='done'),pending=all.reduce((n,b)=>n+(b.files.length-b.nextIndex),0);$('#pendingUploads').textContent=`${pending} pending`;if(!all.length){el.className='empty';el.textContent='No pending uploads.';return}el.className='';el.innerHTML=(state.lastUploadError?`<div class="uploaderror">Last error: ${esc(state.lastUploadError)}</div>`:'')+all.map(b=>`<div class="job"><div class="jobname">${b.files.length-b.nextIndex} of ${b.files.length} videos pending</div><div class="jobmeta">Saved ${fmt(b.createdAt)} · resumes when this app is open</div></div>`).join('')}

function setMode(mode){state.mode=mode;$('#modeRandom').classList.toggle('active',mode==='random');$('#mode24').classList.toggle('active',mode==='24h');$('#modeFixed').classList.toggle('active',mode==='fixed');$('#modeMonthly').classList.toggle('active',mode==='monthly');$('#randomTimes').style.display=mode==='random'?'grid':'none';$('#fixedTimes').style.display=mode==='fixed'?'block':'none';$('#mode24Note').style.display=mode==='24h'?'block':'none';$('#monthlyFields').style.display=mode==='monthly'?'block':'none';$('#scheduleDate').closest('.field').style.display=mode==='monthly'?'none':'block';$('#scheduleSummary').style.display=mode==='monthly'?'none':'block';updateMonthlySummary()}
$('#scheduleBtn').onclick=saveBatchAndUpload;
$('#modeRandom').onclick=()=>setMode('random');$('#mode24').onclick=()=>setMode('24h');$('#modeFixed').onclick=()=>setMode('fixed');$('#modeMonthly').onclick=()=>setMode('monthly');
['#monthlyStart','#monthlyEnd','#monthlyDaily'].forEach(sel=>$(sel)?.addEventListener('input',updateMonthlySummary));
$('#selectAllAccounts').onclick=()=>{state.accounts.slice(0,15).forEach(a=>state.selected.add(a.id));saveSelection();renderChips();updateMonthlySummary()};$('#clearAccounts').onclick=()=>{state.selected.clear();saveSelection();renderChips();updateMonthlySummary()};
$('#queueSearch').oninput=renderQueue;$('#queueFilter').onchange=renderQueue;$('#retryFailed').onclick=async()=>{try{const r=await api('/api/jobs/retry-failed',{method:'POST'});toast(`${r.retried||0} failed jobs queued`);refreshAll(false)}catch(e){toast(e.message)}};$('#refreshPublished').onclick=()=>refreshPublishedExact(true);$('#refreshQueue').onclick=()=>refreshAll(false);$('#deleteFailed').onclick=deleteAllFailed;$('#refreshAccounts').onclick=()=>refreshAll(false);
$('#publishedAccountFilter')?.addEventListener('change',async e=>{state.publishedAccount=e.target.value;await loadPublishedAll(false);renderPublished();refreshGrowthAnalytics()});$('#refreshGrowth')?.addEventListener('click',refreshGrowthAnalytics);

$('#retryPendingBtn').onclick=()=>{state.lastUploadError='';resumeUploads()};$('#clearPendingBtn').onclick=clearPendingUploads;
$('#refreshAllBtn').onclick=()=>refreshAll();$('#storageRefreshBtn').onclick=()=>refreshSystem();
$('#pauseAllMobile').onclick=async()=>{if(!confirm('Pause ALL scheduled Instagram posting? Queued jobs will be kept.'))return;try{await api('/api/scheduler/pause',{method:'POST'});toast('All posting paused');await refreshAll(false)}catch(e){toast(e.message)}};
$('#resumeAllMobile').onclick=async()=>{try{const r=await api('/api/scheduler/resume',{method:'POST'});toast(`Posting resumed · ${r.rebasedJobs||0} overdue job(s) re-spaced`);await refreshAll(false)}catch(e){toast(e.message)}};
$('#driveConnectBtn').onclick=()=>{if(!state.backend){toast('Backend URL save karo.');return}window.open(state.backend+'/api/google-drive/connect','_blank','noopener');toast('Google Drive authorization opened. Return here and tap Refresh Status.')};
$('#driveTestBtn').onclick=async()=>{try{const r=await api('/api/drive-test');toast(r.uploadedAndDeleted?'Drive upload + delete test passed ✅':'Drive test completed');await refreshSystem()}catch(e){toast('Drive test: '+e.message)}};

$('#connectAccount').onclick=async()=>{const label=$('#accLabel').value.trim(),igUserId=$('#accIgId').value.trim(),accessToken=$('#accToken').value.trim();if(!label||!igUserId||!accessToken){toast('Saare account fields fill karo.');return}try{const r=await api('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label,igUserId,accessToken})});if(r.backupBlob){const raw=localStorage.getItem(backupKey()),arr=raw?JSON.parse(raw):[];arr.push(r.backupBlob);localStorage.setItem(backupKey(),JSON.stringify([...new Set(arr)]))}$('#accToken').value='';state.selected.add(r.id);saveSelection();toast('Account connected');await refreshAll(false)}catch(e){toast(e.message)}};
$('#saveBackend').onclick=async()=>{const u=cleanUrl($('#backendUrl').value);if(!/^https:\/\//i.test(u)){toast('HTTPS backend URL dalo.');return}state.backend=u;localStorage.setItem('iap_backend_url',u);loadSelection();await refreshAll()};

function initDate(){const d=new Date(),today=dateKey(d);$('#scheduleDate').value=today;$('#monthlyStart').value=today;$('#monthlyEnd').value=dateKey(new Date(d.getFullYear(),d.getMonth()+1,0));$('#monthlyDaily').value='50'}
async function init(){initDate();setMode('random');updateMonthlySummary();state.backend=cleanUrl(localStorage.getItem('iap_backend_url')||'https://insta-auto-publisher-backend.onrender.com');$('#backendUrl').value=state.backend;loadSelection();if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{})}await renderUploadMini();await refreshAll(false);setInterval(()=>refreshJobsOnly(),10000);setInterval(()=>refreshSystem(),60000)}
init();
